using System;
using System.Collections.Generic;

/// <summary>
/// Member Class: 
/// The member class stores all of the data for each member that uses the Pizza Anonymous system.
///  
/// Author: Ryan Schwartz
/// Date Created: November 6, 2014
/// Last Modified By: Ryan Schwartz
/// Date Last Modified: November 6, 2014
/// </summary>
public class Member
{
    // Member's name with get/set properties.
    private String name;
    public string Name
    {
        get { return name; }
        set { name = value; }
    }

    // Member's id with get property. This value is uniquely autogenerated by MemberManager and cannot be changed.
    private int id;
    public int Id
    {
        get { return id; }
    }

    // Member's address with get/set properties.
    private String streetAddress;
    public String StreetAddress
    {
        get { return streetAddress; }
        set { streetAddress = value; }
    }

    // Member's city with get/set properties.
    private String city;
    public String City
    {
        get { return city; }
        set { city = value; }
    }

    // Member's state with get/set properties.
    private String state;
    public String State
    {
        get { return state; }
        set { state = value; }
    }

    // Member's zip code with get/set properties.
    private int zipCode;
    public int ZipCode
    {
        get { return zipCode; }
        set { zipCode = value; }
    }

    // Member's zip code with get/set properties.
    private bool suspended;
    public bool Suspended
    {
        get { return suspended; }
        set { suspended = value; }
    }

    /// <summary>
    /// This is the only constructor for Member and must be passed parameters (no default constructor)
    /// </summary>
    /// <param name="n">Member name</param>
    /// <param name="i">Generated ID</param>
    /// <param name="sa">Member address</param>
    /// <param name="c">Member city</param>
    /// <param name="s">Member state</param>
    /// <param name="zc">Member zip code</param>
    public Member(String n, int i, String sa, String c, String s, int zc)
    {
        name = n;
        id = i;
        streetAddress = sa;
        city = c;
        state = s;
        zipCode = zc;
        suspended = false;
    }

    public String toString()
    {
        return "\n" +
               "  Name:    " + name + "\n" +
               "  ID:      " + id + "\n" +
               "  Address: " + streetAddress + "\n" +
               "           " + city + ", " + state + " " + zipCode + "\n";
    }
}
